### ISSUE TITLE
New 3.9 version available

### ISSUE THREAD

**Issue by Gloom536** [rigwild/DofusPouletFlemmards-cracked#1]
New 3.9 version available since june 2023, do you think you could crack it? DPF isn't available on discord and doesn't answer DM. So even if I want to but his latest version, this isn't possible.

**Comment by rigwild** [comment]
I can do it if you provide me with the executable

**Comment by Gloom536** [comment]
[DofusPouletFlemmards_3.9_2.exe.zip](https://github.com/rigwild/DofusPouletFlemmards-cracked/files/12410875/DofusPouletFlemmards_3.9_2.exe.zip)
 Here it is, I got it from someone who has access to it, I can't verify if it's warez free or anything, but it seems like it's legit. He sent it to me within few minutes I asked for it, I don't think he would have time to pack a virus or anything in this time.

**Comment by Gloom536** [comment]
Let me know if I should send it to you from another way.

**Comment by rigwild** [comment]
Done https://github.com/rigwild/DofusPouletFlemmards-cracked/releases/tag/3.9.2
