### ISSUE TITLE
Have you seen the update of my other issue? No news since 3 weeks + :(

### ISSUE THREAD

**Issue by Gloom536** [rigwild/DofusPouletFlemmards-cracked#2]
Hi, have you seen the answer I sent in my issue? You asked for the updated exe of DPF, I provided it but got no news. I just want to know if you got notified that I sent you the exe or if it is still unread :P It's ok if you need time to crack this, but I just wanted to know if you saw it and it's in the to do list :)

https://github.com/rigwild/DofusPouletFlemmards-cracked/issues/1

https://github.com/rigwild/DofusPouletFlemmards-cracked/files/12410875/DofusPouletFlemmards_3.9_2.exe.zip

If I need to send the exe from another way (email or other), just tell me and I'll do :)

**Comment by rigwild** [comment]
Hey, the tool I used to crack it is not free anymore

https://ioninja.com/plugins/pipe-monitor.html

I'm not willing to pay for it, and i didn't find a free equivalent that can monitor named pipes constantly

**Comment by Gloom536** [comment]
You cant use an old version available in their achive in their website that supported free trial? If not, I just contacted them by email to know if it's possible to get a trial for the pipe monitor

**Comment by Gloom536** [comment]
<img width="749" alt="image" src="https://github.com/rigwild/DofusPouletFlemmards-cracked/assets/105163385/4410c21a-24f1-434e-a072-e19d51aa218a">

https://ioninja.com/account/capabilities.html

You should be able to have a 14 days trial to use those feature. Can you check this?

**Comment by rigwild** [comment]
Nice, will try
