### ISSUE TITLE
Remove "Dofuspouletflemmards" from details, tray, etc

### ISSUE THREAD

**Issue by Gloom536** [rigwild/DofusPouletFlemmards-cracked#4]
Do you think you could remove the name "Dofuspouletflemmard" from task viewer/detail/process, etc. so that if Ankama Mods scan our process it won't obviously show we use this software. It would only show as a random AHK script that could or couldn't be related to Dofus. It would be less obvious for ban purpose.

Maybe include that with the 3.9 release if possible :)

**Comment by Gloom536** [comment]
Or can I just change it myself in the ahk file where it is written Dofuspouletflemmard here and below?
<img width="605" alt="image" src="https://github.com/rigwild/DofusPouletFlemmards-cracked/assets/105163385/e61e0efb-c2ce-4d77-a000-cf10f5fdd150">

**Comment by rigwild** [comment]
Hey, in latest release I renamed some visible references to "d-p-f" https://github.com/rigwild/DofusPouletFlemmards-cracked/releases/tag/3.9.2

See https://github.com/rigwild/DofusPouletFlemmards-cracked/blob/master/v3.9.2/crack.patch

---

I left the saved files paths (in my_documents) the same, so people don't have to reconfigure everything when updating

If you want to change everything, do your edits in `3_cracked.ahk` with a big replace all of "DofusPouletFlemmards"
